### ISSUE TITLE
Find a way to include a ABOUT.md

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/railtoolkit.github.io#4]
each project can have a ABOUT.md which is rendered for the site!

**Comment by apriljunge** [comment]
Should the source be github or https://repository.ivev.bau.tu-bs.de/ ? Both works.
It's also possible to have this configurable for each project.

**Comment by kaat0** [comment]
To have it configurable for each project seems a good idea to me!

**Comment by apriljunge** [comment]
Projects can now have a `aboutfile` parameter. Only markdown files should be referenced.
You can comment out the readme.md line locally to see that it works.

For now github and IfeV (gitea) urls can be parsed. This can be extended anytime.
:warning: To work properly repository urls must have a trainling slash.

If you agree you can close this issue.

https://github.com/railtoolkit/railtoolkit.github.io/blob/b037f433dc47d73f7726e2cf2ca2b1debcbf0bc3/content/projects/tikz-trackschematic.md?plain=1#L4-L6

https://github.com/railtoolkit/railtoolkit.github.io/blob/b037f433dc47d73f7726e2cf2ca2b1debcbf0bc3/content/projects/edugame-railway-operation.md?plain=1#L4-L6
